services:
  node:
    working_dir: /usr/src/app
    image: node:24
    volumes:
      - ./:/usr/src/app

  postgres:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"